// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bachelor-service/app"
)

// Injectors from wire.go:

func NewApp() (app.App, error) {
	db := ProviderDb()
	service := ProviderService(db)
	handler := ProviderHandler(service)
	appApp := app.App{
		H: handler,
	}
	return appApp, nil
}
